name: Test

on:
  - pull_request
  - push

jobs:

  Lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run test:lint

  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build

  Chrome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: tsc
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum npm run test:blink

  Firefox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: tsc
    - run: sudo apt-get install xvfb
    - run: xvfb-run --auto-servernum npm run test:gecko
